### ISSUE TITLE
Bug: incorrect flags in HW zones if HuntHelper map isn't open

### ISSUE THREAD

**Issue by burnnie** [img02/HuntHelper#41]
Hi,

I found a problem with the flags from HW zones being slightly off.
The reason for this is that the variable _mapZoneMaxCoordSize only gets updated if the HuntHelper map window is open.

Thanks for all your work.

**Comment by img02** [comment]
Thanks for tracking it down, fixed it.

**Comment by burnnie** [comment]
Wow, that was fast. Thank you!
