### ISSUE TITLE
Can't resize map window

### ISSUE THREAD

**Issue by grxvy** [img02/HuntHelper#42]
https://i.imgur.com/6VeFH40.png

Playing in 1440p, running the latest version, not sure what other information I could provide that would be useful. Unsure if this is a feature or a bug, led to believe it's a bug from the image on the main page being far bigger than the one on my screen. 

I can resize all other Hunt Helper windows normally by dragging the corner, however this one I cannot and the corner turns red.

**Comment by img02** [comment]
Need to drag the corner of the map, not the options dropdown (you can click the cog wheel to hide the options menu).
