### ISSUE TITLE
Can't display map images on CN Client

### ISSUE THREAD

**Issue by KirisameVanilla** [img02/HuntHelper#44]
the same question with #29 
i disable the plugin and then enable it, and find no error log in '/xllog'
and this problem only matters CN client.

**Comment by img02** [comment]
Unfortunately I can't test on CN client.

But I know CN is a different version from global, and CN Dalamud is different from normal Dalamud.

So I can't really help if there is no error message.

**Comment by KirisameVanilla** [comment]
got it:(
thx for your reply!
