### ISSUE TITLE
UpdateLastSeen probably should update mark coordinates as well

### ISSUE THREAD

**Issue by DivineRock** [img02/HuntHelper#52]
https://github.com/img02/HuntHelper/blob/609ca34e0f757eb92bb6d61c28f6ee89133bcbab/HuntHelper/Managers/Hunts/TrainManager.cs#L90

If you forget to clear a-marks train in /hht after switching servers (or from yesterday) then only “Last Seen” column is updated and coordinates remain the same from previous scout. _Mildlyinfuriating_ when you realize that after the fact

**Comment by img02** [comment]
Maybe a pop up showing the conflicts would be preferrable?

It doesn't update coordinates for a similar situation, if someone gives you a bad / old import code, it's assumed your hunt train data is more accurate.

The only reason it updates last seen time would be in a situation with multiple people scouting all over the place over like an hour, then data is consolidated with the 'freshest' sighting. Then someone might want to double check a hunt that's 50 minutes old or something.

**Comment by DivineRock** [comment]
Hmmm... I think I get it. Maybe I'll come up with something later, closing issue for now. Thank you!
