### ISSUE TITLE
Minimizing Hunt Train window is affecting other imgui windows

### ISSUE THREAD

**Issue by kousukekun1** [img02/HuntHelper#54]
As title says. Minimizing the /hht window seems to affect other imgui windows.

I've tested this with only HuntHelper, SimpleTweaks and Orchestrion enabled. 

https://github.com/user-attachments/assets/f0175241-c652-4fa0-9334-cb9a726dcce1

**Comment by img02** [comment]
fixed, thank you. 

working on some other stuff atm and since this is minor, it won't be released straight away.
