### ISSUE TITLE
/hhc kills are not counted

### ISSUE THREAD

**Issue by ssss142** [img02/HuntHelper#55]
I am using JP client.
As the title says, kills are not counted.
The character name is full name and the log display is enabled.

`は、カラナシ・ユメミを倒した。`

**Comment by ssss142** [comment]
Collecting does not count multiple acquisitions.
Maybe because it's “はドワーフ綿花×2を入手した。”

**Comment by img02** [comment]
I believe Forgiven Pedantry spawn needs 50 gathering attempts, not 50 total cotton boll.

Some websites says collect 50 cotton boll, but I don't think this is correct. I think Faloop data is more accurate:

![image](https://github.com/user-attachments/assets/7fd5ade3-716d-4cda-861d-12325a8fc978)

fixed okina counter, it will be in the next update.
![image](https://github.com/user-attachments/assets/bccd103c-826f-4111-8b53-f38677fbc65f)

I think the others are working? I tested 'レーシー' and 'ディアッカ'

**Comment by ssss142** [comment]
I understand that it is the number of times the cotton is earned.
When you get more than one at a time it doesn't count as one time.

**Comment by ssss142** [comment]
![image](https://github.com/user-attachments/assets/ae4e3814-3ed6-48bb-b183-660a66ce243d)
'レーシー' and 'ディアッカ' worked.
