### ISSUE TITLE
[Change Request][QoL] Show spawn points by default

### ISSUE THREAD

**Issue by KyonKyonxox** [img02/HuntHelper#62]
In the latest version, there's a new option that lets me select which Marks' spawn points I want to see. Great for scouting since it leaves out the spots only the B ranks use. 
Overall I really like the feature, but it caused a small confusion. I opened HH, installed the maps, and could barely see the spawn points. I checked a bunch of different settings until I checked the newly added "select Mark groups" options, and then things went back to normal. 
As keeping all spawn points visible emulates the behavior before the change [thus streamlining the user experience], would it be possible to change it so all 3 groups are selected by default on installation/settings reset?

**Comment by img02** [comment]
fixed
